### ISSUE TITLE
Develop seller-related API endpoints

### ISSUE THREAD

**Issue by tuantran0910** [tuantran0910/rainbow#23]
Since we are going to create an API for book-ecommerce purpose, we need API endpoints that interacts with sellers. Here is an example of seller when crawling Tiki [website](https://tiki.vn/nha-sach-tiki/c8322)

```yaml
"current_seller": {
   "id": 1,
   "sku": "9831074249227",
   "name": "Tiki Trading",
   "link": "https://tiki.vn/cua-hang/tiki-trading",
   "logo": "d1/3f/ae/13ce3d83ab6b6c5e77e6377ad61dc4a5.jpg",
   "price": 105000,
   "product_id": "275702540",
   "store_id": 40395,
   "is_best_store": false,
   "is_offline_installment_supported": null
}
```

We only need some fields like `name`, `link`, `logo`. Create CRUD endpoints.

> Note: If we get the logo field, the full link will be: `https://vcdn.tikicdn.com/ts/seller/d1/3f/ae/13ce3d83ab6b6c5e77e6377ad61dc4a5.jpg`.
